### ISSUE TITLE
More robust selection

### ISSUE THREAD

**Issue by cjaoude** [mradamh/sublime-unquote#2]
This is a nice package, but it needs to be easier or more robust. Having to select the text exactly is slow, extra work.

It should be that it deletes the nearest quotes. So you just click inside a quoted string, and it just deletes out the nearest quotes. That would be a lot faster.

Unfortunately, I don't know python or Sublime API, or I'd be happy to implement. If you could please add this feature. Thanks.

**Comment by mradamh** [comment]
thanks for the suggestions.  i don't really know python or the sublime API either, this was just a weekend experiment.  

I'd be happy to review PRs with improvements.  Closing this issue for now.
